# Edit this file by hand. Using `pnpm config` reformats the file and removes all comments.

packages:
  - "components/**"
  - "packages/*"
  - "proprietary/*"
  - "packages/web-components/*"

allowBuilds:
  "@parcel/watcher": true
  core-js: false
  esbuild: true

# Configure pnpm so peer dependencies must be explicitly added instead of being automatically installed.
autoInstallPeers: false

# Configure pnpm so it only installs package versions that have been published on the npm registry for at least 24 hours
# (1440 minutes). This helps mitigate the risk of supply chain attacks by avoiding newly published, potentially
# malicious versions. Keep this in sync with npm-check-updates's `cooldown` configuration.
minimumReleaseAge: 1440

# Make an exception for trusted packages, notably our own
minimumReleaseAgeExclude:
  - "@amsterdam/*"
  - "@gemeente-denhaag/*"
  - "@gemeente-rotterdam/*"
  - "@nl-design-system/*"
  - "@nl-design-system-candidate/*"
  - "@nl-design-system-community/*"
  - "@nl-design-system-unstable/*"
  - "@nl-rvo/*"
  - "@rijkshuisstijl-community/*"
  - "@utrecht/*"

# Override vulnerable dependency versions.
overrides:
  "@babel/runtime@<7.26.10": "^7.26.10"
  "@formio/protected-eval": "1.2.3-rc.2"
  "dompurify@<3.4.11": "^3.4.11"
  "js-cookie@<3.0.6": "^3.0.6"
  "js-yaml@<4.1.2": "^4.1.2"
  "read-yaml-file@1.1.0": "2.1.0"
  "shell-quote@<1.8.4": "^1.8.4"
  "uuid@<11.1.1": "^11.1.1"

# Apply patches to fix issues in dependencies that have not yet been resolved by the maintainers. This allows us to
# continue using the affected packages while waiting for official fixes.
# See https://github.com/alex3165/react-leaflet-draw/issues/195
patchedDependencies:
  react-leaflet-draw@0.20.6: patches/react-leaflet-draw@0.20.6.patch

packageExtensions:
  "@open-formulieren/sdk@3.5.4":
    dependencies:
      lodash: "^4.17.21"

# Configure pnpm to save exact version numbers (not including ^ or ~) in package.json. Lock dependencies to specific
# versions to ensure reproducible installs and prevent automatic upgrades to newer minor or patch releases.
saveExact: true
savePrefix: ""

# Configure pnpm to not fail when there are missing or invalid peer dependencies in the tree.
strictPeerDependencies: false

provenance: true

workspaceConcurrency: 8
