import './index.scss';
export * from './Table';
export * from './TableCell';
export * from './TableRow';
export * from './TableFoot';
export * from './TableCol';
export * from './TableBody';
export * from './TableCaption';
export * from './TableColGroup';
export * from './TableHead';
export * from './TableHeader';
